name: Linting Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for Linting Errors
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          clangFormatVersion: 13
          extensions: 'cpp,h'
          inplace: ${{ github.ref != 'refs/heads/master' }}
          style: chromium

      - name: Committing Clang-format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref != 'refs/heads/master'
        with:
          commit_author: GitHub Actions <actions@github.com>
          commit_message: 'fix: Linting Issues'
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          disable_globbing: true
